### ISSUE TITLE
Convert JPEG file to PNG

### ISSUE THREAD

**Issue by mrsamirr** [Coderich-Community/python4#1]
Script to convert JPEG file into PNG format

**Comment by saranshs17** [comment]
Hi , can you please tell from where should i take input file or i should write the code to take the path of input.jpg file

**Comment by mrsamirr** [comment]
Here are the steps which u can follow :
1. Add a library reference (import the library) to your Python project.
2. Load JPEG file with an instance of Workbook.
3.Convert JPEG to PNG by calling Workbook.save method.
Get the conversion result of JPEG to PNG.

**Comment by saranshs17** [comment]
pls check this PR https://github.com/Coderich-Community/python4/pull/11
